# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bca61aa101c1dcfa2fd6f341caf99f9d69898960f4bc16a01704e2a4eb27b4556cc04d2b879e076b0f21ac27e3f3199e995ebbe1c6ed15232f0bb8c45ecec01

test:
  secret_key_base: b1a261274e7d29db8b39703353dca218a897973458045643d7da4426bdf2735da565d252bc226358c2aa73e932e16850641f754e550796e1f169ca1ef8128a41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
